spring:
  profiles:
    active: local
  datasource:
    hikari:
      max-lifetime: 58000

    username: root
    password: masterpw
    url: jdbc:mysql://127.0.0.1:3306/subway?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
        format_sql: true
        show_sql: true

#
#spring.profiles.active=local
#
#spring.datasource.hikari.max-lifetime=58000
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=
#spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#
#spring.datasource.username=root
#spring.datasource.password=123456789a
#spring.datasource.url=jdbc:mysql://211.254.213.210:3306/testSubway?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver