spring:
  cache:
    type: redis
  redis:
    host: 172.25.192.116
    port: 6379
  profiles:
    active: application-local
  datasource:
    hikari:
      max-lifetime: 58000
    username: root
    password: masterpw
    url: jdbc:mysql://172.25.192.166:3306/subway?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"


  metrics:
    tags:
      application: ${spring_application_name}

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json,image/jpeg,image/jpg
    min-response-size: 10240
  tomcat:
    threads:
      max: 200 # 활성화 할수있는 Thread 총 개수
      min-spare: 30 # 항상 활성화 되어있는(idle) thread개수
    max-connections: 8192 # 수립 가능한 Connection 총 개수
    accept-count: 100 # 작업 큐의 사이즈
    connection-timeout: 20000 #timeout 판단 기준, 20초


actuator_endpoint_user: xx
actuator_endpoint_password: xx